sudo: false
language: node_js
node_js:
  - node
cache: npm

script:
  - npm start

deploy:
   provider: script
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   on:
    branch: leeformento/travis-ci
